### ISSUE TITLE
support for vue-jest@v5

### ISSUE THREAD

**Issue by kazupon** [intlify/vue-i18n-jest#23]

**Comment by XavierChevalier** [comment]
It does not seem to support version 5.
When I try to run tests, I have this exception:
```
 ● Test suite failed to run

  TypeError: codes.forEach is not a function

    at node_modules/@vue/vue3-jest/lib/generate-code.js:70:13
        at Array.forEach (<anonymous>)
    at generateCode (node_modules/@vue/vue3-jest/lib/generate-code.js:69:24)
    at Object.module.exports [as process] (node_modules/@vue/vue3-jest/lib/process.js:171:18)
    at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:620:31)
    at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
    at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:823:19)
```

With this Jest configuration:
```js
{
  // ...
  transform: {
    '^.+\\.ts$': 'ts-jest',
    '^.+\\.vue$': '@vue/vue3-jest',
  },
  globals: {
    'vue-jest': {
      transform: {
        i18n: 'vue-i18n-jest',
      },
    },
}
```

It's fail here:

https://github.com/vuejs/vue-jest/blob/6edfa9cd93be05ca4c9c41849db668dbf2ae92d5/packages/vue3-jest/lib/generate-code.js#L70-L72

I tried to debug, and the value of variable `codes` is a string:
```js
"undefined.__i18n = ['{"en":{...},"fr":{...}}']"
```

This string is not iterable here.

My dependencies version:
```json
"devDependencies": {
  "@babel/core": "^7.16.0",
  "@intlify/vite-plugin-vue-i18n": "^3.2.1",
  "@intlify/vue-i18n-loader": "^4.0.1",
  "@vue/test-utils": "^2.0.0-rc.16",
  "@vue/vue3-jest": "^27.0.0-alpha.4",
  "babel-loader": "^8.2.3",
  "jest": "^27.4.1",
  "ts-jest": "^27.0.7",
  "typescript": "^4.4.3",
  "vue-i18n-jest": "^1.1.1",
  "vue-loader": "^16.8.3",
  "vue-tsc": "^0.3.0"
}
```

**Comment by XavierChevalier** [comment]
After investigating, I tried to change the code to be compatible with `vue-jest@5`. I will open a PR soon.

Several changes are to be expected:
- In the `process` function, the `vueOptionsNamespace` argument has been renamed to `componentNamespace`.
See [[vue-jest] feat: support custom blocks for Vue 3 #364](https://github.com/vuejs/vue-jest/pull/364/files#diff-cfd5ddc1cd42bb1028d4e575cae04d2a77d492d99903ce57fae41a13473c48b0R18-R26)
- `vue-jest` [did the work so that we could return an array of strings directly](https://github.com/vuejs/vue-jest/pull/364/files/522f99c353ee34e71627b6b7f10ababb3de299d8#diff-cfd5ddc1cd42bb1028d4e575cae04d2a77d492d99903ce57fae41a13473c48b0R68-R74).
